import React from 'react';
import { DAGData } from '../types';
import { FileText, BookOpen, Clock, AlertTriangle } from 'lucide-react';

interface NarrativeViewProps {
  data: DAGData;
}

export function NarrativeView({ data }: NarrativeViewProps) {
  // Split narrative by paragraphs
  const paragraphs = data.narrative.split('\n\n').filter(p => p.trim() !== '');

  return (
    <div className="max-w-4xl mx-auto py-8 px-6">
      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 md:p-12 text-slate-800 font-serif leading-loose text-base md:text-lg relative overflow-hidden">
        {/* Decorative corner */}
        <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-50/50 rounded-bl-full pointer-events-none" />
        <BookOpen className="absolute top-6 right-6 w-8 h-8 text-indigo-100 pointer-events-none" />

        <h2 className="text-2xl md:text-3xl font-semibold text-slate-900 mb-8 font-sans tracking-tight">
          Causal Summary: {data.target_event.name}
        </h2>
        
        <div className="flex items-center gap-4 text-sm font-sans text-slate-500 mb-10 pb-6 border-b border-slate-100">
          <div className="flex items-center gap-1.5 bg-slate-50 px-3 py-1.5 rounded-lg">
            <Clock className="w-4 h-4" />
            <span className="font-medium">{data.target_event.date}</span>
          </div>
          <div className="flex items-center gap-1.5 bg-indigo-50 text-indigo-700 px-3 py-1.5 rounded-lg font-medium">
            <FileText className="w-4 h-4" />
            <span>Auto-generated by Renderer Agent</span>
          </div>
        </div>

        <div className="space-y-8">
          {paragraphs.map((p, i) => (
            <p key={i} className="leading-relaxed">
              {p}
            </p>
          ))}
        </div>

        <div className="mt-12 pt-8 border-t border-slate-100 flex items-start gap-4 text-sm font-sans bg-amber-50 text-amber-900 p-6 rounded-xl">
          <AlertTriangle className="w-6 h-6 shrink-0 mt-0.5 text-amber-600" />
          <div>
            <h4 className="font-bold mb-1">Agent Confidence Note</h4>
            <p className="text-amber-800/80">
              This narrative was synthesized directly from the Causal DAG (Directed Acyclic Graph). 
              The events described have an average source confidence score of 0.92 based on {data.events.length} extracted historical nodes. 
              Switch to the <strong>Timeline View</strong> to trace exact citations and causal logic paths.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
